### ISSUE TITLE
Using https for the endpoint results in error

### ISSUE THREAD

**Issue by zaifastafa** [oblakstudio/ddev-minio#34]
Hi, I am using the add-on with my shopware setup. If I use `https` for the endpoint, then I get the error messaged that `Could not contact remote server.` . If I use only `http` then everything works fine in terms of connectivity and uploading the files, but when rendering those files from the server, I get failed response in status. 

the following is my shopware.yaml configuration flie: 

```
shopware:
  filesystem:
    public:
      type: "amazon-s3"
      url: 'https://abc.ddev.site:9090/media'
      config:
        bucket: "media"
        endpoint: "http://minio:10101"
        use_path_style_endpoint: true
        region: 'local'
        credentials:
          key: ddevminio
          secret: ddevminio
        options:
          visibility: "public"
    theme:
      type: "amazon-s3"
      url: 'https://abc.ddev.site:9090/theme'
      config:
        bucket: "theme"
        endpoint: "http://minio:10101"
        use_path_style_endpoint: true
        region: 'local'
        credentials:
          key: ddevminio
          secret: ddevminio
        options:
          visibility: "public"
  cdn:
    strategy: id
 ```

The files are there on the server: 

![image](https://github.com/oblakstudio/ddev-minio/assets/24492269/62ed1421-c5d8-4d7d-9a8d-f6eb2fe15271)

And when loading the file on the front also, I get 200 OK status, but it gets failed somehow: 

![image](https://github.com/oblakstudio/ddev-minio/assets/24492269/20a0b001-efa2-4834-ade4-6ea32699faac)

What could be the problem? 

Thanks.
